export const flashcards = [
  {
    id: "1",
    collectionId: "2",
    question: "What is the powerhouse of the cell?",
    answer: "The mitochondrion",
    isLiked: false,
  },
  {
    id: "2",
    collectionId: "2",
    question: "What is the process by which plants make their food?",
    answer: "Photosynthesis",
    isLiked: false,
  },
  {
    id: "3",
    collectionId: "2",
    question: "What are the building blocks of proteins?",
    answer: "Amino acids",
    isLiked: false,
  },
  {
    id: "4",
    collectionId: "2",
    question: "What is the largest organ in the human body?",
    answer: "The skin",
    isLiked: false,
  },
  {
    id: "5",
    collectionId: "2",
    question: "What is the main function of red blood cells?",
    answer: "To transport oxygen",
    isLiked: false,
  },
  {
    id: "6",
    collectionId: "5",
    question: "What is the capital of France?",
    answer: "Paris",
    isLiked: false,
  },
  {
    id: "7",
    collectionId: "5",
    question: "Which river is the longest in the world?",
    answer: "The Nile",
    isLiked: false,
  },
  {
    id: "8",
    collectionId: "5",
    question: "What is the largest desert in the world?",
    answer: "The Sahara Desert",
    isLiked: false,
  },
  {
    id: "9",
    collectionId: "5",
    question: "Which country has the most population?",
    answer: "China",
    isLiked: false,
  },
  {
    id: "10",
    collectionId: "5",
    question: "What is the smallest continent by land area?",
    answer: "Australia",
    isLiked: false,
  },
  {
    id: "11",
    collectionId: "10",
    question: "What does HTML stand for?",
    answer: "HyperText Markup Language",
    isLiked: false,
  },
  {
    id: "12",
    collectionId: "10",
    question:
      "What is the name of the first electronic general-purpose computer?",
    answer: "ENIAC",
    isLiked: false,
  },
  {
    id: "13",
    collectionId: "10",
    question: "Who is known as the father of computers?",
    answer: "Charles Babbage",
    isLiked: false,
  },
  {
    id: "14",
    collectionId: "10",
    question: "What does CPU stand for?",
    answer: "Central Processing Unit",
    isLiked: false,
  },
  {
    id: "15",
    collectionId: "10",
    question: "What is the main function of RAM?",
    answer: "To store data temporarily",
    isLiked: false,
  },
  {
    id: "16",
    collectionId: "3",
    question: "What is the pH level of pure water?",
    answer: "7",
    isLiked: false,
  },
  {
    id: "17",
    collectionId: "3",
    question: "What is the periodic table?",
    answer: "A table of chemical elements arranged by atomic number",
    isLiked: false,
  },
  {
    id: "18",
    collectionId: "3",
    question: "What is the process of converting a liquid into vapour called?",
    answer: "Evaporation",
    isLiked: false,
  },
  {
    id: "19",
    collectionId: "4",
    question: "What is the force that keeps us on the ground?",
    answer: "Gravity",
    isLiked: false,
  },
  {
    id: "20",
    collectionId: "4",
    question: "What is the speed of light?",
    answer: "299,792,458 meters per second",
    isLiked: false,
  },
  {
    id: "21",
    collectionId: "4",
    question: "Who developed the theory of relativity?",
    answer: "Albert Einstein",
    isLiked: false,
  },
  {
    id: "22",
    collectionId: "8",
    question: "Who painted the Mona Lisa?",
    answer: "Leonardo da Vinci",
    isLiked: false,
  },
  {
    id: "23",
    collectionId: "8",
    question:
      "What is the primary colour of the sky in the painting 'Starry Night' by Van Gogh?",
    answer: "Blue",
    isLiked: false,
  },
  {
    id: "24",
    collectionId: "8",
    question:
      "What is the art technique that uses small dots to create a larger image?",
    answer: "Pointillism",
    isLiked: false,
  },
  {
    id: "25",
    collectionId: "9",
    question: "Who composed the Four Seasons?",
    answer: "Antonio Vivaldi",
    isLiked: false,
  },
  {
    id: "26",
    collectionId: "9",
    question: "What is the musical term for 'loud'?",
    answer: "Forte",
    isLiked: false,
  },
  {
    id: "27",
    collectionId: "9",
    question:
      "What is the term for a piece of music written for a solo instrument?",
    answer: "Sonata",
    isLiked: false,
  },
  {
    id: "28",
    collectionId: "1",
    question: "What is the value of pi up to two decimal places?",
    answer: "3.14",
    isLiked: false,
  },
  {
    id: "29",
    collectionId: "1",
    question: "What is the square root of 144?",
    answer: "12",
    isLiked: false,
  },
  {
    id: "30",
    collectionId: "1",
    question: "How many sides does a hexagon have?",
    answer: "Six",
    isLiked: false,
  },
];

export const collections = [
  {
    id: "1",
    title: "Mathematics",
    color: "#c28375",
  },
  {
    id: "2",
    title: "Biology",
    color: "#DAF7A6",
  },
  {
    id: "3",
    title: "Chemistry",
    color: "#75c297",
  },
  {
    id: "4",
    title: "Physics",
    color: "#7597c2",
  },
  {
    id: "5",
    title: "Geography",
    color: "#ab75c2",
  },
  {
    id: "6",
    title: "History",
    color: "#c28375",
  },
  {
    id: "7",
    title: "Literature",
    color: "#DAF7A6",
  },
  {
    id: "8",
    title: "Art",
    color: "#75c297",
  },
  {
    id: "9",
    title: "Music",
    color: "#7597c2",
  },
  {
    id: "10",
    title: "Informatics",
    color: "#ab75c2",
  },
];
